= Resources for Behaviour-Driven Development

== https://www.youtube.com/watch?v=w7NPpEvC1dE[BDD Overview]. footnote:[Bradley, M. (2016). 02 BDD Overview]
===== Video Link _12:03_ ►

*Behaviour-Driven Development (BDD)*

* What is it?
* What are the benefits?
* Who Participates?

*Rhythm of BDD*

* How does it fit in the agile process?

*Gherkin language to create living requirements*

* How do we define system behaviour?

== https://vimeo.com/65160463[Behavior Driven Development with Cucumber]
===== Video link _10:40_

► "Today we are going to talk about Behavior Driven Development with Cucumber. I have set up a little app and show you some examples in Ruby."

Clemens Helm explains what Cucumber is used for, that it uses feature files and how you write scenarios; "a scenario is a sequence of steps that describe what exactly it is that you want to acheive". This covers "given steps", "when steps" and "then steps", as well as the advantages of using cucumber; descriptions make it clear what the code is doing and the steps are reusable.

== https://www.youtube.com/watch?v=vrry-I4NXCI[Talk by Gordon Force about BDD at the San Francisco Java User Group]
===== Video Link _59:21_ ►

- Short Defenition  _0:58_
- Second-Generation  _1:53_
- Outside-In Methodology _2:48_
- BDD Stories - Multiple-Stakeholder _3:55_
* The Team Writes the Story - "the team writes them and the stakeholders describe the features and the outcomes; this is what I want and this is what I need it to do." _11:40_
* BDD Story Format _13:41_
- Pull Based is better than Push Based _18:26_
* The Pull Cycle _21:22_
* The Red-Green-Refractor TDD Cycle _22:41_
* BDD Testing is not Unit Testing _24:05_
* The BDD Cycle _26:28_
- jbehave _27:36_
* jbehave Usage _32:48_
* Q&A on jbehave example _44:15_

== https://inviqa.com/bdd-guide[A guide to BDD, outlined by Inviqa]
===== Web Page
► "The concept of BDD was introduced by Dan North, an experienced technology and organisational consultant based in London, as a means of clearing confusion between testers, developers and business people."

- **What is it?**

* Key Benefits of BDD

- **Key Elements**

* Starting with a Goal
* Impact Mapping
* Value and Complexity Analysis
* Planning in Examples
* Usage-Centered Design
* Ubiquitous Language
* Example Workshop: Introducing the Three Amigos
* Development Through Examples
* The BDD Loops

- **Q&A**

* What was the biggest pain or problem that you were looking to address when you introduced BDD?
8 Why does BDD work? What is its essence / core?
* What is the biggest impediment to BDD?

- **How we use it**

- **Glossary**


== https://pythonhosted.org/behave/philosophy.html[Further example of the uses of BDD] 
===== Web Page

► "BDD focuses on obtaining a clear understanding of desired software behavior through discussion with stakeholders. It extends TDD by writing test cases in a natural language that non-programmers can read."

► "The practices of BDD include:

- Establishing the goals of different stakeholders required for a vision to be implemented
- Drawing out features which will achieve those goals using feature injection
- Involving stakeholders in the implementation process through outside–in software development
- Using examples to describe the behavior of the application, or of units of code
- Automating those examples to provide quick feedback and regression testing
- Using ‘should’ when describing the behavior of software to help clarify responsibility and allow the software’s functionality to be questioned
- Using ‘ensure’ when describing responsibilities of software to differentiate outcomes in the scope of the code in question from side-effects of other elements of code.
- Using mocks to stand-in for collaborating modules of code which have not yet been written"

== https://dannorth.net/introducing-bdd/[The development of BDD from Test Driven Development]
===== Web Page
► This article explains how BDD was developed to improve upon the limitations of https://github.com/Driven-Development/documentation/blob/master/TestDD/Link.adoc[TDD]. 
It better accomodates the use of http://agilemodeling.com/essays/agileAnalysis.htm[agile analysis] 
and https://www.thoughtworks.com/insights/blog/acceptance-test-automation[automated acceptance testing]. 

== http://behaviourdriven.org/[BDDWiki]
===== Web Page
► "BDD relies on the use of a very specific (and small) vocabulary to minimise miscommunication and to ensure that everyone – the business, developers, testers, analysts and managers – are not only on the same page but using the same words."

► The pages leads to a more in depth explaination of BDD:

- Introduction : A brief overview
- The BDDProcess : A description of a development process using BDD
- BehaviourDrivenAnalysis : How do we approach analysis for BDD?
- BehaviourDrivenProgramming : What changes do we make to our approach to programming?
- DanNorth has written an article describing how BDD evolved.
- DaveAstels has written an article about BDD in Ruby.
- Implementations : Tools for implementing BDD.

== https://prezi.com/pcffgdstea5e/stories-using-behavior-driven-dev/[Stories using Behavior Driven Dev]
===== Prezi Powerpoint

► This presentation outlines how BDD can improve communication between the customers, developers and stakeholders involved. 

► BDD is a Combination of Test Driven Development and Domain Driven Development , and it's based on three core principles; Business and technology should refer to the same system in the same way; any system should have an identifiable and varifiable value to the business; up-front analysis, design and planning all have a diminishing return.

► Test Driven Development is making the software right, whereas Behaviour Driven Development is making the right software.

► The use of stories to improve communication and how to create a good story to reach the goals of the project. This includes a Story Title, Narrative and Scenarios.

== https://www.infoq.com/news/2015/02/bdd-ddd[Behaviour-Driven Development Combined with Domain-Driven Design] 
===== Web page

► DDD can also be used in combination with https://github.com/Driven-Development/documentation/blob/master/BehaviourDD/Links.adoc[BDD].

► BDD can become more like DDD; "by talking with domain experts clarifying naming, finding missing relations and so on, scenarios can be written with more details and when written in a common language shared by business people and developers, a ubiquitous language will emerge, a key concept in DDD."
