= Resources for Readme Driven Development 

http://tom.preston-werner.com/2010/08/23/readme-driven-development.html[Readme Driven Development from Tom Preston-Werner]► This outlines why a Readme should be included in documentation and its place as a subset of Documentation-Driven Development. 

It also includes advantages of a Readme 	

•Laying out a clear plan of what you're writing 	

•"As a byproduct of writing a Readme in order to know what you need to implement, you’ll have a very nice piece of documentation sitting in front of you." 

•A Readme provides a document to anyone else working on the project, allowing them to work on other projects that will onterface with the new code before you's even finished 

•"The simple act of writing down a proposed solution means everyone has a concrete idea that can be argued about and iterated upon."

https://www.youtube.com/watch?v=4qD3KmGLnss[Presentation at DevFest Vienna 2014]► Implications and benifits of having a Readme and its links to a design-driven way of thinking, as well as how it fits into Documentation Driven Development and others


