= Resources for Readme Driven Development 

== http://tom.preston-werner.com/2010/08/23/readme-driven-development.html[Readme Driven Development from Tom Preston-Werner] 
===== Web page

► This outlines why a Readme should be included in documentation and its place as a subset of https://github.com/Driven-Development/documentation/blob/master/DocumentationDD/Links.adoc[Documentation-Driven Development]. 

It also includes advantages of a Readme; 	

•Laying out a clear plan of what you're writing 	

•"As a byproduct of writing a Readme in order to know what you need to implement, you’ll have a very nice piece of documentation sitting in front of you." 

•A Readme provides a document to anyone else working on the project, allowing them to work on other projects that will onterface with the new code before you's even finished 

•"The simple act of writing down a proposed solution means everyone has a concrete idea that can be argued about and iterated upon."

https://elliot.land/readme-driven-development[The Humble Readme] 

► This goes into a bit more detail on what is in the Readme and how it's beneficial for the person writing the documentation and the reader.

== https://www.youtube.com/watch?v=4qD3KmGLnss[Presentation at DevFest Vienna 2014] 
===== Video link _23.25_

► Implications and benifits of having a README and its links to a design-driven way of thinking, as well as how it fits into https://github.com/Driven-Development/documentation/blob/master/DocumentationDD/Links.adoc[Documentation Driven Development] and others.

► Having a document of the requirements before hand rather than having to document everything afterward.

► README Driven Development brings a Design element.

► How does RDD relate to https://github.com/Driven-Development/documentation/blob/master/BehaviourDD/Links.adoc[BDD]? _5:30_

* README is an intoduction to the code rather than a whole documentation

► Detecting complexity early on _6:50_

* Pro Tip: Write your issues like documentation 

► Write the README first as a scaffold for what you're going to do _7:57_

*Benefits of RDD _8:53_*

* Gives a clear idea of the project so code doesn't need to be changed every time you want to adjust it.
* Provides a reference for later documentation.
* Writing documentation after a project is a lot harder than writing a Readme beforehand.
* Co-workers can work on other projects that will interface with your code
* Easier to have a discussion based on something written down.
* Goals can be pinned down by the developers and consumers better.
* Github showcases the Readme on the main project page
* It's open-source compatible

* Pro Tip: Keep your Readme open at all times.
* Free Bonus Feature: no teams are just sitting pretty.
* Pro Tip: Implementing RDD/DDD to BDD or TDD can be a simple step. _13:25_
* Pro Tip: Make writing or updating documentation a required first step of your development process.
* Pro Tip: Include documentation changes as part of your reviews.

*Pitfalls of RDD _14:22_*

* An overgenerlization of a good idea, and need to fit into the documentation process of the project.
* Some READMEs are written about what the code is aiming to do or could do, rather than what it is actually able to do.
* It's not a substitute for documentation 

*What makes a good README _15:48_*

* Should describe the project.
* Format correctly (for browser viewing).
* Have code samples and examples.
* Have community, licensing details and how to contribute.
* Explain where the code may have it's limits and don't over-state it.

== https://www.youtube.com/watch?v=2dAK42B7qtw[Write the Readable README]
===== Video link _22.48_

== https://www.youtube.com/watch?v=23xzRCoDZf4[Ignite Rails: Matt Parker - README Driven Development]
===== Video link _5.31_

► README is part of having an open source community.

► README is for the users.

► It's a story with a beginning, middle and end.

* Act One - "the hook"
* Act Two - Tutorial
* Act Three - Get Out Quickly

► Write the README first

== https://www.youtube.com/watch?v=L3SZGil9xok[Readme Driven Development by Petro Sasnyk]
===== Video link _56:43_

== https://ponyfoo.com/articles/readme-driven-development[README Driven Development]
===== Web page

► "README-first is a powerful notion. You sit down, you design your library, flesh out an http://www.webopedia.com/TERM/A/API.html[API], write it down, and get to coding."

► This documentation is more efficient to change than rewriting tests in https://github.com/Driven-Development/documentation/blob/master/TestDD/Link.adoc[TDD]

► It's important for an open-source community, as "without thorough, well-written documentation, consumers are at a complete loss as to how to use a library."


