= Resources for Readme Driven Development 

== http://tom.preston-werner.com/2010/08/23/readme-driven-development.html[Readme Driven Development from Tom Preston-Werner] 
===== Web page

► This outlines why a Readme should be included in documentation and its place as a subset of https://github.com/Driven-Development/documentation/blob/master/DocumentationDD/Links.adoc[Documentation-Driven Development]. 

It also includes advantages of a Readme; 	

•Laying out a clear plan of what you're writing 	

•"As a byproduct of writing a Readme in order to know what you need to implement, you’ll have a very nice piece of documentation sitting in front of you." 

•A Readme provides a document to anyone else working on the project, allowing them to work on other projects that will onterface with the new code before you's even finished 

•"The simple act of writing down a proposed solution means everyone has a concrete idea that can be argued about and iterated upon."

 https://elliot.land/readme-driven-development[The Humble Readme] 
===== Web page

► This goes into a bit more detail on what is in the Readme and how it's beneficial for the person writing the documentation and the reader.

== https://www.youtube.com/watch?v=4qD3KmGLnss[Presentation at DevFest Vienna 2014] 
===== Video link _23.25_

► Implications and benifits of having a README and its links to a design-driven way of thinking, as well as how it fits into https://github.com/Driven-Development/documentation/blob/master/DocumentationDD/Links.adoc[Documentation Driven Development] and others.

== https://www.youtube.com/watch?v=2dAK42B7qtw[Write the Readable README]
===== Video link _22.48_

== https://www.youtube.com/watch?v=23xzRCoDZf4[Ignite Rails: Matt Parker - README Driven Development]
===== Video link _5.31_

► README is part of having an open source community.

► README is for the users.

► It's a story with a beginning, middle and end.

* Act One - "the hook"
* Act Two - Tutorial
* Act Three - Get Out Quickly

► Write the README first

== https://www.youtube.com/watch?v=L3SZGil9xok[Readme Driven Development by Petro Sasnyk]
===== Video link _56:43_

== https://ponyfoo.com/articles/readme-driven-development[README Driven Development]
===== Web page

► "README-first is a powerful notion. You sit down, you design your library, flesh out an http://www.webopedia.com/TERM/A/API.html[API], write it down, and get to coding."

► This documentation is more efficient to change than rewriting tests in https://github.com/Driven-Development/documentation/blob/master/TestDD/Link.adoc[TDD]

► It's important for an open-source community, as "without thorough, well-written documentation, consumers are at a complete loss as to how to use a library."


