= Resources for Documentation Driven Development 

== https://gist.github.com/zsup/9434452[Documentation-Driven Development (DDD)] 

===== Web Page

► A definition of DDD and a simple order of operations when utilising it.

► "...from the perspective of a user, if a feature is not documented, then it doesn't exist, and if a feature is documented incorrectly, then it's broken."

== https://www.youtube.com/watch?v=x5rGUqRWlK8[DDD from Daniele Procida at PyCon 2016]

===== Video link _28:01_

► An overview of what Documentation Driven Development is, as well as its uses and importance to the a Webserver like Django.
► 

- *Documentation-Driven Development* _2.58_
- *Don't document your code, code your documentation* _3.32_
- *Lessons from the Django project* _5.00_
* -Django's good documentation is good for Django
* -Software is not the only thing that developes
* -What does documentation mean for the development of communities and programmers?
- Developing a community _8.29_
* -Information and documentation as product and content
* -Information and documentation as process and activity
* -Good documentation shows respect
* -Django's documentation informs its community
- Developing programmers _17.49_
* -Django's documentation structure guides new contributions
* -Contributions to Django's documentation are taken seriously and held to the highest standards
* -Contributions to Django's documentation are valued
* -Documenting code is the best possible way to understand it
* -Django's documentation advances those who contribute to it 
* -Django does documentation-driven development 
- *What can your project do?* _23.17_

== http://collectiveidea.com/blog/archives/2014/04/21/on-documentation-driven-development/[Collective idea- On Documentation-Driven Development]
===== Web Page

► The article talks about this "lesser-known concept of “documentation-driven development”". It hightlights the importance of the README, "it has the ability to give a high level view of your code, communicating its overarching purpose." It also mentions http://www.webopedia.com/TERM/A/API.html[APIs] and their experience at Collective Idea, "writing documentation first provides a space in which server and client teams can collaborate", " [DDD] elevates writing documentation to the same level of importance as writing code... this gives the reviewer insight into the “why” behind a set of code changes."

== http://thinkingphp.org/spliceit/docs/0.1_alpha/pages/ddd_info.html[SpliceIt!-Documenation v0.1 ALPHA]
===== Web Page

► Benefits and limitations of DDD

*The good*

- Keeps you from over-complicating things.
- Your project will always be very well documented.
- Helps Planning.
- Creates user-friendly software.
- Keeps up motivation.

*And the bad*

- Time consuming.
- I can be confusing.
