= Resources for Feature Driven Development

== http://www.arrkgroup.com/thought-leadership/feature-driven-development-a-guide/[Feature Driven Development: A Guide] footnote:[Lawton, R. (2015). Feature Driven Development: A Guide | Arrk Group.]
===== Web page

► This covers the 5 processes of FDD;

* Develop an overall model
* Build a feature list
* Plan by features
* Design by feature
* Build by feature

As well as best practices designed for software engineering and the pros and cons of FDD

== https://www.youtube.com/watch?v=D7f4ztJIHwo[Feature Driven Development] footnote:[Ebbers, H. (2016).]
===== Video link _22:00_

► "This talk shows Best Practices that can be used to develop application in an agile and feature driven workflow. Companies like flickr use this development process internally and even Martin Fowler defined a part of the process as FeatureToggle .In the talk I will start with the definition of feature tasks and what steps and methods are needed to define them. Next to this an application is shown that was developed by the use of FeatureToggles. Here different architecture approaches in Java will be shown. Next to the architecture of an application the development workflows must be changed to create applications in a feature driven way, too. In some examples best practices to handle the new workflows will be shown.Methods and tools like the GitFlow, GitLab, the Java Togglz API and Jira will be shown in this talk."

► What is a feature?
* Notion of adding a feature using a simple example

► Using a feature branch.
* A branch allows a feature to be developed while the application can be released without unfinished features in it.
* There are issues with merging different features, but dark launching and small branches are some of the solutions that can be used to solve this.

== http://agilemodeling.com/essays/fdd.htm[Feature Driven Development (FDD) and Agile Modeling] footnote:[Ambler, S. (2014). Feature Driven Development (FDD) and Agile Modeling.]
===== Web page

► Has more in depth information about the origins of FDD.

► Outlines what a 'feature' is; "A feature is a small, client-valued function expressed in the form <action><result><object>."

► Uses a diagram to explain the FDD project lifecycle.

► Explains how agile modeling can be applied to FDD.

► http://www.nebulon.com/fdd/[Agile Software Development using Feature Driven Development (FDD)]


