= Resources for Domain Driven Development

== http://www.methodsandtools.com/archive/archive.php?id=97[An Introduction to Domain Driven Design]
===== Web page

► "In this article I’m going to run through some of the main patterns of DDD, pick up on some areas where newbies seem to struggle, and highlight some tools and resources to help you apply DDD in your work."

► "The philosophy of domain-driven design... is about placing our attention at the heart of the application, focusing on the complexity that is intrinsic to the business domain itself."

► The article explains a model-driven design that DDD uses, "the model is the set of concepts that we select to be implemented in software, represented in code and any other software artifact used to construct the delivered system. In other words, the code is the model."

► This explains how you "develop a ubiquitous language. If an idea can’t easily be expressed then it indicates a concept that’s missing from the domain model and the team work together to figure out what that missing concept is."

► Bounded context is also explained; "users relate to the concepts of the model in a particular way, and the terminology of the model makes sense to these users but not necessarily to anyone else outside that context."

== https://www.infoq.com/presentations/ddd-net-1[Exploring Domain Driven Design Implementation Patterns in .NET, Part 1/2]
===== Video link _52:19_

► "Steve Bohlen introduces DDD principles and concepts, and explores various patterns -Repositories, Specifications, Entities, Value Objects, Services, etc. - useful for implementing DDD in .NET code."

► Concepts behind DDD.

=== https://www.infoq.com/presentations/ddd-net-2[Exploring Domain Driven Design Implementation Patterns in .NET, Part 2/2]
===== Video link _1:02:10_

► Individual building blocks, code examples.

== https://www.youtube.com/watch?v=RNUn2R7TptM[Domain-Driven Design: Bradley Holt Found Line]
===== Video link _1:05:37_

► 

- What is a Domain? _0:00:30_
- What is a Model? _0:02:05_
- Case Study: Three Dimensional Animation _0:07:15_
* Working with Domain experts 
- Identify your core domain _0:09:25_
- There are always multiple models _0:11:30_
* Bounded context
* Ubiquitous language
- Strategic Design _0:14:00_
* Context Map
* Relationship Patterns
- Building Blocks _0:16:42_
* Entity ○ Value Object ○ Aggregate ○ Aggregate Root ○ Repository ○ Service
- Model Exploration _0:23:20_
- Ubiquitous Language _0:26:30_
* Domain concept: Election event
* Election Event ○ Ballot item ○ Election ○ District ○ Winning Threshold
* Scenario ○ Elecation Aggregate ○ Election Entity (Aggregate Root) ○ Candidate Entity ○ Winning Policy Value Object
* Code Probe ○ Election Scenario as Test ○ Challenge Model with more Scenarios ○ 
- Supple Design _0:45:13_
* Closure of operations ○ Totaling Ballot Item Results ○ Other Techniques ○ Is the intention clear? ○ Side-effect free  ○ Assert Preconditions and Postconditions 
- Advanced Topics _0:52:10_
* Domain Event ○ Event Log 
- Command-Query Responsibility Segregation (CQRS) _0:54:09_
* Write Model/Read Model
- Q&A

== https://www.youtube.com/watch?v=d8V_yCuXx2Y[Domain Driven Design talk, given at Imagine Easy Solutions in New York City.]
===== Video link _59:33_

► https://www.dropbox.com/s/27oq6ewyjo44i3a/DDDppt.pptx?dl=0[Powerpoint presentation given]

A Tech Talk about Domain Driven Design, given at Imagine Easy Solutions in New York City. We cover some of the basics of Domain Driven Design, such as:

- What is a "domain?"
- What is a "domain expert?"
- What is a "model?"
- How do I work with a domain expert to create a model?
- The building blocks of the model, including:
* Entities ○ Value Objects ○ Factories ○ Services ○ Repositories
- We also synthesize all of these things into a single, layered architecture. But most of that section got cut off because the camera died.

== http://dddcommunity.org/learning-ddd/what_is_ddd/[Domain-driven design] ► A short intoduction to DDD      
===== Web page

►  "Its premise is:

	- Place the project’s primary focus on the core domain and domain logic
	- Base complex designs on a model
	- Initiate a creative collaboration between technical and domain experts to iteratively cut ever closer to the conceptual heart of the problem."

== https://www.youtube.com/watch?v=pL9XeNjy_z4[Domain Driven Design Through Onion Architecture]  
===== Video link _28:30_

► Senior Software Developer Wade Waldron does a presentation on the structure of DDD and how it functions in colaboration with Onion Architecture to improve code quality. There is more on this https://www.infoq.com/news/2015/02/bdd-ddd[here]
► 

== http://www.drdobbs.com/architecture-and-design/domain-driven-design-the-good-and-the-ch/240169117[Domain-Driven Design: The Good and The Challenging]
===== Web Page

► "In DDD, once you understand the business domain your software is to address, then all you have to do is build a layered architecture where the business logic is split into two distinct modules — core domain logic and the application logic."
► "The scenario for which DDD provides invaluable help is understanding the intricacies of the business domain."
► The starting point of DDD is that it serves the purpose of design far before it may serve the purpose of implementation."
► "...a lot of time is lost in working out implementation details"

== https://www.infoq.com/news/2015/02/bdd-ddd[Behaviour-Driven Development Combined with Domain-Driven Design] 
===== Web page

► DDD can also be used in combination with https://github.com/Driven-Development/documentation/blob/master/BehaviourDD/Links.adoc[BDD]
► BDD can become more like DDD; "by talking with domain experts clarifying naming, finding missing relations and so on, scenarios can be written with more details and when written in a common language shared by business people and developers, a ubiquitous language will emerge, a key concept in DDD."
